export const USER_LOADED = 'USER_LOADED';
export const MOBILE_LOADED = 'MOBILE_LOADED';
export const INIT_SINGLETON_REQUEST_DISPATCHER = 'INIT_SINGLETON_REQUEST_DISPATCHER';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_CHANGED = 'PROFILE_CHANGED';
export const PROFILE_IMAGE_CHANGED = 'PROFILE_IMAGE_CHANGED';
export const ID_LOADED = 'ID_LOADED';
export const PERSON_ID_LOADED = 'PERSON_ID_LOADED';
export const COMPANY_LOADED = 'COMPANY_LOADED';
export const COMPANY_CHANGED = 'COMPANY_CHANGED';
export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';
export const EMPLOYEE_REMOVED = 'EMPLOYEE_REMOVED';
export const EMPLOYEE_CHANGED = 'EMPLOYEE_CHANGED';
export const EMPLOYEE_SET = 'EMPLOYEE_SET';
export const SIM_ADDED = 'SIM_ADDED';
export const SIM_REMOVED = 'SIM_REMOVED';
export const SIM_CHANGED = 'SIM_CHANGED';
export const SIM_SET = 'SIM_SET';
export const CALL_ADDED = 'CALL_ADDED';
export const SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED';
export const USAGE_UPDATED = 'USAGE_UPDATED';
export const PRESENCE_UPDATED = 'PRESENCE_UPDATED';
export const QUEUE_ADDED = 'QUEUE_ADDED';
export const QUEUE_REMOVED = 'QUEUE_REMOVED';
export const QUEUE_CHANGED = 'QUEUE_CHANGED';
export const QUEUE_SET = 'QUEUE_SET';
export const PACKAGE_ADDED = 'PACKAGE_ADDED';
export const PACKAGE_CHANGED = 'PACKAGE_CHANGED';
export const PACKAGE_REMOVED = 'PACKAGE_REMOVED';
export const PACKAGE_SET = 'PACKAGE_SET';
export const ORDERED_PACKAGE_SET = 'ORDERED_PACKAGE_SET';
export const ORDERED_PACKAGE_ADDED = 'ORDERED_PACKAGE_ADDED';
export const ORDERED_PACKAGE_CHANGED = 'ORDERED_PACKAGE_CHANGED';
export const ORDERED_PACKAGE_REMOVE = 'ORDERED_PACKAGE_REMOVE';
export const ORDERED_PACKAGE_LOADED = 'ORDERED_PACKAGE_LOADED';
export const INCOMING_CALL_UPDATED = 'INCOMING_CALL_UPDATED';
export const VERIFY_UPDATED = 'VERIFY_UPDATED';
export const LOGGED_OUT = 'LOGGED_OUT';
export const STARTUP = 'STARTUP';

// export const TYPES_ARRAY = [
//     USER_LOADED,
//     MOBILE_LOADED,
//     INIT_SINGLETON_REQUEST_DISPATCHER,
//     PROFILE_LOADED,
//     PROFILE_CHANGED,
//     PROFILE_IMAGE_CHANGED,
//     ID_LOADED,
//     PERSON_ID_LOADED,
//     COMPANY_LOADED,
//     COMPANY_CHANGED,
//     EMPLOYEE_ADDED,
//     EMPLOYEE_REMOVED,
//     EMPLOYEE_CHANGED,
//     EMPLOYEE_SET,
//     SIM_ADDED,
//     SIM_REMOVED,
//     SIM_CHANGED,
//     SIM_SET,
//     CALL_ADDED,
//     SUBSCRIPTION_UPDATED,
//     USAGE_UPDATED,
//     PRESENCE_UPDATED,
//     QUEUE_ADDED,
//     QUEUE_REMOVED,
//     QUEUE_CHANGED,
//     QUEUE_SET,
//     PACKAGE_ADDED,
//     PACKAGE_CHANGED,
//     PACKAGE_REMOVED,
//     PACKAGE_SET,
//     ORDERED_PACKAGE_SET,
//     ORDERED_PACKAGE_ADDED,
//     ORDERED_PACKAGE_CHANGED,
//     ORDERED_PACKAGE_REMOVE,
//     ORDERED_PACKAGE_LOADED,
//     INCOMING_CALL_UPDATED,
//     VERIFY_UPDATED,
//     LOGGED_OUT,
//     STARTUP
// ];
